services:
  - type: web
    name: erp-decision-support
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SOURCE_DB_NAME
        value: erp_source
      - key: WAREHOUSE_DB_NAME
        value: erp_warehouse
      - key: MONGODB_URI
        sync: false
